modLoader = "javafml"
loaderVersion = "[${forge_min_version},)"
issueTrackerURL = "https://github.com/${github_user}/${github_repo}/issues"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "${ae2_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
mandatory = false
versionRange = "${jei_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "crafttweaker"
mandatory = false
versionRange = "${crt_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = false
versionRange = "${archi_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "rhino"
mandatory = false
versionRange = "${rhino_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "${kube_version_range}"
ordering = "AFTER"
side = "BOTH"
